/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GuiForm;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;

/**
 *
 * @author N-vision
 */
public class Student_Info extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Student_Info.class.getName());

    /**
     * Creates new form Student_Info
     */
    public Student_Info() {
        initComponents();
        loadStudentData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        studentId = new javax.swing.JLabel();
        studentIdTxt = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        grade = new javax.swing.JLabel();
        gradeTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentInfoTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentId.setText("Student ID");
        Panel1.add(studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 29, -1, -1));
        Panel1.add(studentIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 26, 211, -1));

        name.setText("Name");
        Panel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 57, -1, -1));
        Panel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 54, 211, -1));

        age.setText("Age");
        Panel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 85, -1, -1));
        Panel1.add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 211, -1));

        grade.setText("Grade");
        Panel1.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 113, -1, -1));
        Panel1.add(gradeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 211, -1));

        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        Panel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 138, -1, -1));

        studentInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Age", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentInfoTable);
        if (studentInfoTable.getColumnModel().getColumnCount() > 0) {
            studentInfoTable.getColumnModel().getColumn(0).setResizable(false);
            studentInfoTable.getColumnModel().getColumn(1).setResizable(false);
            studentInfoTable.getColumnModel().getColumn(2).setResizable(false);
            studentInfoTable.getColumnModel().getColumn(3).setResizable(false);
        }

        Panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 380, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
         String id = studentIdTxt.getText();
        String name = nameTxt.getText();
        String age = ageTxt.getText();
        String grade = gradeTxt.getText();

        if (id.isEmpty() || name.isEmpty() || age.isEmpty() || grade.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill out the form");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) studentInfoTable.getModel();
        model.insertRow(0, new Object[]{id, name, age, grade});

        studentIdTxt.setText("");
        nameTxt.setText("");
        ageTxt.setText("");
        gradeTxt.setText("");

        saveAllToFile(); // Call method to overwrite file            
        }//GEN-LAST:event_addBtnActionPerformed

        private void saveAllToFile() {
        DefaultTableModel model = (DefaultTableModel) studentInfoTable.getModel();

        try (FileWriter writer = new FileWriter("C:\\Users\\N-vision\\Documents\\NetBeansProjects\\GUI\\src\\GuiForm\\student_Info.txt", false);
             PrintWriter pWriter = new PrintWriter(writer)) {

            for (int i = 0; i < model.getRowCount(); i++) {
                String id = model.getValueAt(i, 0).toString();
                String name = model.getValueAt(i, 1).toString();
                String age = model.getValueAt(i, 2).toString();
                String grade = model.getValueAt(i, 3).toString();

                pWriter.println(id + "," + name + "," + age + "," + grade);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving to file: " + e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

         private void loadStudentData() {
        DefaultTableModel model = (DefaultTableModel) studentInfoTable.getModel();
        model.setRowCount(0);

        File file = new File("C:\\Users\\N-vision\\Documents\\NetBeansProjects\\GUI\\src\\GuiForm\\student_Info.txt");
        if (!file.exists()) return;

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length == 4) {
                    model.addRow(data);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Student_Info().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel age;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JLabel grade;
    private javax.swing.JTextField gradeTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel studentId;
    private javax.swing.JTextField studentIdTxt;
    private javax.swing.JTable studentInfoTable;
    // End of variables declaration//GEN-END:variables
}
